name: Java CI with Gradle

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: ./gradlew test -Denv=test

    - name: Copy History
      uses: actions/checkout@v2
      if: always()
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build Report
      uses: simple-elf/allure-report-action@v1.10
      if: always()
      with:
        allure_results: build/allure-results
        allure_history: allure-history
        keep_reports: 10

    - name: Publish Report
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
